### ISSUE TITLE
[Bug] monday.storage.instance.setItem not storing values between page reloads

### ISSUE THREAD

**Issue by goodpilotfish** [mondaycom/monday-sdk-js#90] opened 2023-04-19 15:19 UTC
**Describe the bug**
monday.storage does not remember setItems between page reloads

**Steps to reproduce**
Working code
1. Add follwing code (a setItem and a getItem)
```
import mondaySdk from "monday-sdk-js";
const monday = mondaySdk();
const KEY = 'key';

monday.storage.instance.setItem(KEY, JSON.stringify({ tjo: 'tjo'})).then(res => {
  monday.storage.instance.getItem(KEY).then(res => {
    console.log(res.data.value); // -----> Correct { value: str, success: true }
  });
});
```
2. Comment out the setItem
```
monday.storage.instance.getItem(KEY).then(res => {
  console.log(res.data.value); 
});
```
4. Reload page --> // -----> Incorrect { value: null, success: true }

**Expected behavior**
Just like localStorage, getItem returns the right value after a page reload. Have I misunderstood anything? Here are the monday (docs)[https://developer.monday.com/apps/docs/mondaystorage]

**Context and environment**
Running the app inside the monday preview mode

**Additional information**
"monday-sdk-js": "^0.3.2"

**Comment by yuhgto** [comment] 2023-04-27 22:43
Hey @goodpilotfish – thanks for reporting this. I can't reproduce it – I always get the correct value when reading from the storage, even without refreshing the page. 

I tried setting the data and then retrieving it immediately. It worked. 

I also tried commenting out one command at a time. It worked. 

What kind of app feature did you test it on? I tried it on a board view and it worked fine.

**Comment by yuhgto** [comment] 2023-05-03 16:37
Heads up, I'm closing this issue. If you're still having trouble with this, please post in our dev community or shoot our technical support team an email so we can help you out! 

Here are the links you need: 
- [monday developer community](https://community.monday.com/c/developers/8)
- [Technical support email](appsupport@monday.com)

**Closed by yuhgto** 2023-05-03 16:37 UTC
